# Generated by Django 3.2.4 on 2021-07-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('flowers', 'Flowers'), ('candles', 'Candles')], max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='photos/products')),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
